// import { Database } from '@/types/supabase';

// type Profile = Database['public']['Tables']['profiles']['Row'] & {
//     media?: Database['public']['Tables']['media']['Row'][];
// };

export const MOCK_PROFILES: any[] = [
    {
        id: 'mock-1',
        ad_id: 'a3k9m',
        display_name: 'Isabella',
        role: 'advertiser',
        gender: 'mulher',
        category: 'Acompanhante', // Added
        is_banned: false,
        created_at: new Date().toISOString(),
        age: 23,
        height: '1.65m',
        weight: '55kg',
        city: 'São Paulo',
        state: 'SP',
        telegram: 'isabellaluxo',
        instagram: 'isabella.luxo',
        twitter: 'isabellax',
        neighborhood: 'Jardins',
        street_address: 'Rua Oscar Freire, 450',
        address_reference: 'Próximo ao shopping Iguatemi',
        latitude: -23.5678,
        longitude: -46.6712,
        price: 300,
        is_online: true,
        verified: true,
        verification_status: 'approved',
        rating: 4.9,
        reviews_count: 124,
        views: 3420,
        services: ['Massagem Relaxante', 'Namoradinha', 'Jantar', 'Viagens', 'Fetiches', 'Beijo na boca', 'Oral até o final'],
        description: 'Olá amores, sou a Isabella. Uma companheira elegante, divertida e muito carinhosa. Adoro conhecer pessoas novas e proporcionar momentos inesquecíveis. Falo inglês e português.',
        hairColor: 'Morena',
        bodyType: 'Magro',
        ethnicity: 'Branca',
        paymentMethods: ['Dinheiro', 'PIX', 'Cartão de Crédito'],
        hasPlace: true,
        videoCall: true,
        media: [
            { id: '1', profile_id: 'mock-1', url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=800&q=80', type: 'image', created_at: '' },
            { id: '1b', profile_id: 'mock-1', url: 'https://images.unsplash.com/photo-1524250502761-1ac6f2e30d43?w=800&q=80', type: 'image', created_at: '' },
            { id: '1v', profile_id: 'mock-1', url: '', type: 'video', created_at: '' }
        ]
    },
    {
        id: 'mock-2',
        ad_id: 'x7b2n',
        display_name: 'Sophie',
        role: 'advertiser',
        gender: 'trans',
        category: 'Massagista', // Added
        is_banned: false,
        created_at: new Date().toISOString(),
        age: 21,
        height: '1.70m',
        weight: '58kg',
        city: 'Rio de Janeiro',
        state: 'RJ',
        telegram: 'sophiesensual',
        instagram: 'sophie.rio',
        twitter: 'sophiex',
        neighborhood: 'Copacabana',
        street_address: 'Avenida Atlântica, 1234',
        address_reference: 'Edifício Copacabana Palace',
        latitude: -22.9735,
        longitude: -43.1866,
        price: 250,
        is_online: false,
        verified: true,
        verification_status: 'approved',
        rating: 4.8,
        reviews_count: 89,
        views: 2890,
        services: ['Massagem Tântrica', 'Iniciantes', 'Casais', 'Oral com camisinha'],
        description: 'Sophie, a sua melhor escolha no Rio. Doce, menina mulher, pronta para realizar suas fantasias mais ocultas com total discrição.',
        hairColor: 'Loira',
        bodyType: 'Mignon',
        ethnicity: 'Branca',
        paymentMethods: ['Dinheiro', 'PIX'],
        hasPlace: false,
        videoCall: true,
        media: [
            { id: '2', profile_id: 'mock-2', url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&q=80', type: 'image', created_at: '' },
            { id: '2b', profile_id: 'mock-2', url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=800&q=80', type: 'image', created_at: '' }
        ]
    },
    {
        id: 'mock-3',
        ad_id: 'k9p4q',
        display_name: 'Valentina',
        role: 'advertiser',
        gender: 'mulher',
        category: 'Acompanhante', // Added
        is_banned: false,
        created_at: new Date().toISOString(),
        age: 25,
        height: '1.68m',
        weight: '60kg',
        city: 'Curitiba',
        state: 'PR',
        telegram: 'valentinadom',
        instagram: 'valentina.curitiba',
        twitter: 'valentinadmx',
        neighborhood: 'Batel',
        street_address: 'Rua Benjamin Constant, 789',
        address_reference: '',
        latitude: -25.4378,
        longitude: -49.2790,
        price: 400,
        is_online: true,
        verified: true,
        verification_status: 'approved',
        rating: 5.0,
        reviews_count: 42,
        views: 2150,
        services: ['Dominatrix', 'Fetiches Pesados', 'Roleplay', 'Sado suave'],
        description: 'Valentina. Atitude e beleza em um só pacote. Se você procura algo fora do comum, acabou de encontrar.',
        hairColor: 'Ruiva',
        bodyType: 'Curvilínea',
        ethnicity: 'Branca',
        paymentMethods: ['Dinheiro', 'PIX', 'Crypto'],
        hasPlace: true,
        videoCall: false,
        media: [
            { id: '3', profile_id: 'mock-3', url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=800&q=80', type: 'image', created_at: '' },
            { id: '3v', profile_id: 'mock-3', url: '', type: 'video', created_at: '' }
        ]
    },
    {
        id: 'mock-4',
        ad_id: 'm2n8x',
        display_name: 'Gabriela',
        role: 'advertiser',
        gender: 'mulher',
        category: 'Massagista', // Added
        is_banned: false,
        created_at: new Date().toISOString(),
        age: 19,
        height: '1.60m',
        weight: '50kg',
        city: 'Belo Horizonte',
        state: 'MG',
        telegram: 'gabibh',
        instagram: 'gabi.massagem',
        twitter: '',
        neighborhood: 'Savassi',
        street_address: '',
        address_reference: 'Próximo ao Parque Municipal',
        latitude: -19.9335,
        longitude: -43.9378,
        price: 200,
        is_online: false,
        verified: false,
        verification_status: null,
        rating: 4.7,
        reviews_count: 15,
        services: ['Massagem', 'Oral', 'Completo', 'Ejaculação corpo'],
        description: 'Gabriela, a mineinha que você sempre sonhou. Carinhosa e safada na medida certa.',
        hairColor: 'Morena',
        bodyType: 'Mignon',
        ethnicity: 'Mulata',
        paymentMethods: ['Dinheiro'],
        hasPlace: false,
        videoCall: true,
        media: [{ id: '4', profile_id: 'mock-4', url: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=800&q=80', type: 'image', created_at: '' }]
    },
    {
        id: 'mock-5',
        ad_id: 'p5q3r',
        display_name: 'Fernanda',
        role: 'advertiser',
        gender: 'mulher',
        category: 'Acompanhante', // Added
        is_banned: false,
        created_at: new Date().toISOString(),
        age: 28,
        height: '1.75m',
        weight: '65kg',
        city: 'Porto Alegre',
        state: 'RS',
        telegram: 'fernandapoa',
        instagram: 'fer.class',
        twitter: 'ferluxury',
        neighborhood: 'Moinhos de Vento',
        street_address: 'Rua Doutor Timóteo, 200',
        address_reference: '',
        latitude: -30.0346,
        longitude: -51.2177,
        price: 350,
        is_online: true,
        verified: true,
        verification_status: 'approved',
        rating: 4.9,
        reviews_count: 210,
        services: ['Acompanhante de Luxo', 'Jantares', 'Eventos', 'Namoradinha'],
        description: 'Fernanda. Classe e sofisticação para homens de bom gosto.',
        hairColor: 'Loira',
        bodyType: 'Fitness',
        ethnicity: 'Branca',
        paymentMethods: ['Dinheiro', 'PIX', 'Cartão de Crédito'],
        hasPlace: true,
        videoCall: false,
        media: [{ id: '5', profile_id: 'mock-5', url: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=800&q=80', type: 'image', created_at: '' }]
    },
    {
        id: 'mock-6',
        ad_id: 's8t4v',
        display_name: 'Julia',
        role: 'advertiser',
        gender: 'mulher',
        category: 'Massagista', // Added
        is_banned: false,
        created_at: new Date().toISOString(),
        age: 22,
        height: '1.67m',
        weight: '56kg',
        city: 'Salvador',
        state: 'BA',
        telegram: 'juliabahia',
        instagram: 'ju.ssalvador',
        twitter: '',
        neighborhood: 'Barra',
        street_address: '',
        address_reference: 'Próximo ao Farol da Barra',
        latitude: -13.0098,
        longitude: -38.5311,
        price: 150,
        is_online: true,
        verified: false,
        verification_status: null,
        rating: 4.5,
        reviews_count: 56,
        services: ['Massagem', 'Relaxamento', 'Oral com camisinha'],
        description: 'Julia. A alegria e o calor da Bahia com você.',
        hairColor: 'Morena',
        bodyType: 'Curvilínea',
        ethnicity: 'Negra',
        paymentMethods: ['Dinheiro', 'PIX'],
        hasPlace: true,
        videoCall: true,
        media: [{ id: '6', profile_id: 'mock-6', url: 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=800&q=80', type: 'image', created_at: '' }]
    },
    {
        id: 'mock-7',
        ad_id: 'w6y2z',
        display_name: 'Camila',
        role: 'advertiser',
        gender: 'trans',
        category: 'Acompanhante', // Added
        is_banned: false,
        created_at: new Date().toISOString(),
        age: 24,
        height: '1.72m',
        weight: '62kg',
        city: 'Brasília',
        state: 'DF',
        telegram: 'camiladf',
        instagram: 'camilatrans',
        twitter: 'camilax',
        neighborhood: 'Asa Sul',
        street_address: 'SQN 304, Bloco E',
        address_reference: '',
        latitude: -15.7975,
        longitude: -47.8919,
        price: 500,
        is_online: false,
        verified: true,
        verification_status: 'approved',
        rating: 5.0,
        reviews_count: 31,
        services: ['Executivos', 'Discrição Total', 'Viagens'],
        description: 'Camila. O segredo mais bem guardado de Brasília.',
        hairColor: 'Preto',
        bodyType: 'Magro',
        ethnicity: 'Oriental',
        paymentMethods: ['Dinheiro', 'PIX', 'Crypto'],
        hasPlace: false,
        videoCall: false,
        media: [{ id: '7', profile_id: 'mock-7', url: 'https://images.unsplash.com/photo-1554151228-14d9def656ec?w=800&q=80', type: 'image', created_at: '' }]
    },
    {
        id: 'mock-8',
        ad_id: 'b4c7d',
        display_name: 'Larissa',
        role: 'advertiser',
        gender: 'mulher',
        category: 'Acompanhante', // Added
        is_banned: false,
        created_at: new Date().toISOString(),
        age: 20,
        height: '1.63m',
        weight: '52kg',
        city: 'Fortaleza',
        state: 'CE',
        telegram: '',
        instagram: 'larissa.praia',
        twitter: '',
        neighborhood: 'Meireles',
        street_address: 'Avenida Beira Mar, 3200',
        address_reference: 'Próximo ao Hotel Gran Marquise',
        latitude: -3.7172,
        longitude: -38.5434,
        price: 200,
        is_online: true,
        verified: true,
        verification_status: 'approved',
        rating: 4.6,
        reviews_count: 78,
        services: ['Namoradinha', 'Praia', 'Diversão', 'Beijo na boca'],
        description: 'Larissa. Venha curtir o sol e o mar comigo.',
        hairColor: 'Loira',
        bodyType: 'Fitness',
        ethnicity: 'Branca',
        paymentMethods: ['Dinheiro', 'PIX'],
        hasPlace: true,
        videoCall: true,
        media: [{ id: '8', profile_id: 'mock-8', url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=800&q=80', type: 'image', created_at: '' }]
    },
    {
        id: 'mock-9',
        ad_id: 'f9g5h',
        display_name: 'Gabriel',
        role: 'advertiser',
        gender: 'homem',
        category: 'Acompanhante', // Added
        is_banned: false,
        created_at: new Date().toISOString(),
        age: 26,
        height: '1.80m',
        weight: '80kg',
        city: 'São Paulo',
        state: 'SP',
        telegram: 'gabrielsp',
        instagram: 'gabriel.boy',
        twitter: 'gabrielx',
        neighborhood: 'Pinheiros',
        street_address: 'Rua Teodoro Sampaio, 123',
        address_reference: '',
        latitude: -23.5647,
        longitude: -46.6926,
        price: 300,
        is_online: true,
        verified: true,
        verification_status: 'approved',
        rating: 4.8,
        reviews_count: 12,
        services: ['Acompanhante', 'Massagem', 'Casais'],
        description: 'Gabriel, discreto e educado, pronto para te servir.',
        hairColor: 'Moreno',
        bodyType: 'Atlético',
        ethnicity: 'Branca',
        paymentMethods: ['Dinheiro', 'PIX'],
        hasPlace: true,
        videoCall: false,
        media: [{ id: '9', profile_id: 'mock-9', url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=800&q=80', type: 'image', created_at: '' }]
    },
    {
        id: 'mock-10',
        ad_id: 'm7n3p',
        display_name: 'Luna',
        role: 'advertiser',
        gender: 'mulher',
        category: 'Massagista',
        is_banned: false,
        created_at: new Date().toISOString(),
        age: 28,
        height: '1.70m',
        weight: '62kg',
        city: 'São Paulo',
        state: 'SP',
        telegram: 'lunamassagem',
        instagram: 'luna.massagem',
        twitter: '',
        neighborhood: 'Vila Madalena',
        street_address: '',
        address_reference: 'Próximo à Praça Benedito Calixto',
        latitude: -23.5489,
        longitude: -46.6928,
        price: 250,
        is_online: true,
        verified: true,
        verification_status: 'approved',
        rating: 4.8,
        reviews_count: 156,
        services: ['Massagem Relaxante', 'Namoradinha'],
        description: 'Luna, especialista em massagens terapêuticas e relaxantes. Ambiente tranquilo e profissional.',
        hairColor: 'Morena',
        bodyType: 'Curvilínea',
        ethnicity: 'Branca',
        paymentMethods: ['Dinheiro', 'PIX', 'Cartão de Crédito'],
        hasPlace: true,
        videoCall: false,
        massageTypes: ['Terapêuticas', 'Relaxantes', 'Corpo a corpo'],
        otherServices: ['Depilação'],
        happyEnding: ['Masturbação'],
        facilities: ['Com local', 'Ducha', 'Maca', 'Óleos essenciais', 'Música relaxante', 'Material descartável'],
        serviceTo: ['Homens', 'Mulheres', 'Casais'],
        media: [{ id: '10', profile_id: 'mock-10', url: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=800&q=80', type: 'image', created_at: '' }]
    },
    {
        id: 'mock-11',
        ad_id: 'q2r8s',
        display_name: 'Aurora',
        role: 'advertiser',
        gender: 'mulher',
        category: 'Massagista',
        is_banned: false,
        created_at: new Date().toISOString(),
        age: 32,
        height: '1.68m',
        weight: '60kg',
        city: 'Rio de Janeiro',
        state: 'RJ',
        telegram: 'auroratantrica',
        instagram: 'aurora.tantrica',
        twitter: '',
        neighborhood: 'Ipanema',
        street_address: 'Rua Visconde de Pirajá, 567',
        address_reference: '',
        latitude: -22.9864,
        longitude: -43.2030,
        price: 400,
        is_online: false,
        verified: true,
        verification_status: 'approved',
        rating: 5.0,
        reviews_count: 89,
        services: ['Massagem Tântrica', 'Namoradinha'],
        description: 'Aurora, terapeuta especializada em massagem tântrica. Experiência transformadora e relaxante.',
        hairColor: 'Ruiva',
        bodyType: 'Fitness',
        ethnicity: 'Branca',
        paymentMethods: ['Dinheiro', 'PIX'],
        hasPlace: true,
        videoCall: false,
        massageTypes: ['Tântricas', 'Relaxantes', 'Corpo a corpo'],
        otherServices: [],
        happyEnding: ['Masturbação', 'Sexo oral'],
        facilities: ['Com local', 'Tatami', 'Óleos essenciais', 'Música relaxante', 'Material descartável'],
        serviceTo: ['Homens', 'Mulheres', 'Casais'],
        media: [{ id: '11', profile_id: 'mock-11', url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=800&q=80', type: 'image', created_at: '' }]
    },
    {
        id: 'mock-12',
        ad_id: 't5v9w',
        display_name: 'Maya',
        role: 'advertiser',
        gender: 'mulher',
        category: 'Massagista',
        is_banned: false,
        created_at: new Date().toISOString(),
        age: 25,
        height: '1.65m',
        weight: '58kg',
        city: 'Belo Horizonte',
        state: 'MG',
        telegram: 'mayamassagem',
        instagram: 'maya.massagem',
        twitter: '',
        neighborhood: 'Savassi',
        street_address: 'Rua Rio de Janeiro, 890',
        address_reference: '',
        latitude: -19.9335,
        longitude: -43.9378,
        price: 200,
        is_online: true,
        verified: false,
        verification_status: null,
        rating: 4.6,
        reviews_count: 42,
        services: ['Massagem Relaxante'],
        description: 'Maya oferece massagens relaxantes e terapêuticas. Ambiente acolhedor e profissional.',
        hairColor: 'Morena',
        bodyType: 'Mignon',
        ethnicity: 'Mulata',
        paymentMethods: ['Dinheiro', 'PIX'],
        hasPlace: true,
        videoCall: true,
        massageTypes: ['Terapêuticas', 'Relaxantes'],
        otherServices: ['Depilação'],
        happyEnding: ['Masturbação'],
        facilities: ['Com local', 'Ducha', 'Maca', 'Material descartável'],
        serviceTo: ['Homens', 'Mulheres'],
        media: [{ id: '12', profile_id: 'mock-12', url: 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=800&q=80', type: 'image', created_at: '' }]
    },
    {
        id: 'mock-13',
        ad_id: 'x3y7z',
        display_name: 'Sofia',
        role: 'advertiser',
        gender: 'mulher',
        category: 'Massagista',
        is_banned: false,
        created_at: new Date().toISOString(),
        age: 30,
        height: '1.72m',
        weight: '65kg',
        city: 'Curitiba',
        state: 'PR',
        telegram: 'sofiamassagem',
        instagram: 'sofia.massagem',
        twitter: '',
        neighborhood: 'Batel',
        street_address: '',
        address_reference: 'Próximo ao Shopping Mueller',
        latitude: -25.4378,
        longitude: -49.2790,
        price: 300,
        is_online: false,
        verified: true,
        verification_status: 'approved',
        rating: 4.9,
        reviews_count: 127,
        services: ['Massagem Relaxante', 'Massagem Tântrica'],
        description: 'Sofia, massagista profissional com especialização em técnicas orientais e tântricas.',
        hairColor: 'Loira',
        bodyType: 'Curvilínea',
        ethnicity: 'Branca',
        paymentMethods: ['Dinheiro', 'PIX', 'Cartão de Crédito'],
        hasPlace: true,
        videoCall: false,
        massageTypes: ['Tântricas', 'Relaxantes', 'Corpo a corpo', 'Terapêuticas'],
        otherServices: [],
        happyEnding: ['Masturbação', 'Sexo oral', 'Penetração'],
        facilities: ['Com local', 'Tatami', 'Ducha', 'Óleos essenciais', 'Música relaxante', 'Material descartável'],
        serviceTo: ['Homens', 'Mulheres', 'Casais', 'Deficientes físicos'],
        media: [{ id: '13', profile_id: 'mock-13', url: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=800&q=80', type: 'image', created_at: '' }]
    },
    {
        id: 'mock-14',
        ad_id: 'a1b5c',
        display_name: 'Lara',
        role: 'advertiser',
        gender: 'mulher',
        category: 'Massagista',
        is_banned: false,
        created_at: new Date().toISOString(),
        age: 27,
        height: '1.63m',
        weight: '55kg',
        city: 'Porto Alegre',
        state: 'RS',
        telegram: 'laramassagem',
        instagram: 'lara.massagem',
        twitter: '',
        neighborhood: 'Moinhos de Vento',
        street_address: 'Avenida Osvaldo Aranha, 400',
        address_reference: '',
        latitude: -30.0346,
        longitude: -51.2177,
        price: 220,
        is_online: true,
        verified: true,
        verification_status: 'approved',
        rating: 4.7,
        reviews_count: 73,
        services: ['Massagem Relaxante'],
        description: 'Lara oferece massagens relaxantes e terapêuticas. Foco no bem-estar e relaxamento.',
        hairColor: 'Morena',
        bodyType: 'Magro',
        ethnicity: 'Branca',
        paymentMethods: ['Dinheiro', 'PIX'],
        hasPlace: true,
        videoCall: false,
        massageTypes: ['Relaxantes', 'Terapêuticas'],
        otherServices: [],
        happyEnding: ['Masturbação'],
        facilities: ['Com local', 'Maca', 'Óleos essenciais', 'Música relaxante'],
        serviceTo: ['Homens', 'Mulheres'],
        media: [{ id: '14', profile_id: 'mock-14', url: 'https://images.unsplash.com/photo-1554151228-14d9def656ec?w=800&q=80', type: 'image', created_at: '' }]
    },
    {
        id: 'mock-15',
        ad_id: 'd4e8f',
        display_name: 'Renata',
        role: 'advertiser',
        gender: 'mulher',
        category: 'Massagista',
        is_banned: false,
        created_at: new Date().toISOString(),
        age: 35,
        height: '1.70m',
        weight: '68kg',
        city: 'Brasília',
        state: 'DF',
        telegram: 'renatamassagem',
        instagram: 'renata.massagem',
        twitter: '',
        neighborhood: 'Asa Sul',
        street_address: 'SQN 404, Bloco C',
        address_reference: '',
        latitude: -15.7975,
        longitude: -47.8919,
        price: 350,
        is_online: false,
        verified: true,
        verification_status: 'approved',
        rating: 4.8,
        reviews_count: 94,
        services: ['Massagem Tântrica', 'Massagem Relaxante'],
        description: 'Renata, terapeuta experiente em massagem tântrica e terapêutica. Ambiente profissional e discreto.',
        hairColor: 'Preto',
        bodyType: 'Curvilínea',
        ethnicity: 'Negra',
        paymentMethods: ['Dinheiro', 'PIX', 'Cartão de Crédito'],
        hasPlace: true,
        videoCall: false,
        massageTypes: ['Tântricas', 'Terapêuticas', 'Relaxantes', 'Corpo a corpo'],
        otherServices: ['Depilação'],
        happyEnding: ['Masturbação', 'Sexo oral'],
        facilities: ['Com local', 'Tatami', 'Ducha', 'Óleos essenciais', 'Música relaxante', 'Material descartável'],
        serviceTo: ['Homens', 'Mulheres', 'Casais'],
        media: [{ id: '15', profile_id: 'mock-15', url: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=800&q=80', type: 'image', created_at: '' }]
    },
    {
        id: 'mock-16',
        ad_id: 'g2h6i',
        display_name: 'Beatriz',
        role: 'advertiser',
        gender: 'mulher',
        category: 'Massagista',
        is_banned: false,
        created_at: new Date().toISOString(),
        age: 29,
        height: '1.67m',
        weight: '61kg',
        city: 'Salvador',
        state: 'BA',
        telegram: 'beatrizmassagem',
        instagram: 'beatriz.massagem',
        twitter: '',
        neighborhood: 'Barra',
        street_address: '',
        address_reference: 'Próximo à praia do Porto da Barra',
        latitude: -13.0098,
        longitude: -38.5311,
        price: 180,
        is_online: true,
        verified: false,
        verification_status: null,
        rating: 4.5,
        reviews_count: 38,
        services: ['Massagem Relaxante'],
        description: 'Beatriz oferece massagens relaxantes com técnicas tradicionais. Ambiente acolhedor.',
        hairColor: 'Morena',
        bodyType: 'Curvilínea',
        ethnicity: 'Negra',
        paymentMethods: ['Dinheiro', 'PIX'],
        hasPlace: true,
        videoCall: true,
        massageTypes: ['Relaxantes', 'Terapêuticas'],
        otherServices: [],
        happyEnding: ['Masturbação'],
        facilities: ['Com local', 'Maca', 'Óleos essenciais'],
        serviceTo: ['Homens', 'Mulheres'],
        media: [{ id: '16', profile_id: 'mock-16', url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&q=80', type: 'image', created_at: '' }]
    },
    {
        id: 'mock-17',
        ad_id: 'j5k9l',
        display_name: 'Mariana',
        role: 'advertiser',
        gender: 'mulher',
        category: 'Massagista',
        is_banned: false,
        created_at: new Date().toISOString(),
        age: 26,
        height: '1.64m',
        weight: '57kg',
        city: 'Fortaleza',
        state: 'CE',
        telegram: 'marianamassagem',
        instagram: 'mariana.massagem',
        twitter: '',
        neighborhood: 'Meireles',
        street_address: 'Rua Monsenhor Tabosa, 1234',
        address_reference: '',
        latitude: -3.7172,
        longitude: -38.5434,
        price: 200,
        is_online: true,
        verified: true,
        verification_status: 'approved',
        rating: 4.7,
        reviews_count: 65,
        services: ['Massagem Relaxante'],
        description: 'Mariana, massagista profissional especializada em relaxamento e bem-estar.',
        hairColor: 'Loira',
        bodyType: 'Fitness',
        ethnicity: 'Branca',
        paymentMethods: ['Dinheiro', 'PIX'],
        hasPlace: true,
        videoCall: false,
        massageTypes: ['Relaxantes', 'Corpo a corpo'],
        otherServices: ['Depilação'],
        happyEnding: ['Masturbação', 'Sexo oral'],
        facilities: ['Com local', 'Ducha', 'Maca', 'Óleos essenciais', 'Música relaxante'],
        serviceTo: ['Homens', 'Mulheres', 'Casais'],
        media: [{ id: '17', profile_id: 'mock-17', url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=800&q=80', type: 'image', created_at: '' }]
    }
];
