// Principais bairros de São Paulo
export const SAO_PAULO_NEIGHBORHOODS = [
    'Jardins',
    'Vila Madalena',
    'Pinheiros',
    'Vila Olímpia',
    'Moema',
    'Itaim Bibi',
    'Brooklin',
    'Bela Vista',
    'Consolação',
    'Liberdade',
    'Centro',
    'República',
    'Vila Mariana',
    'Campo Belo',
    'Santo Amaro',
    'Alto da Boa Vista',
    'Paraíso',
    'Cerqueira César',
    'Higienópolis',
    'Perdizes',
    'Pompeia',
    'Vila Formosa',
    'Tatuapé',
    'Mooca',
    'Brás',
    'Barra Funda',
    'Lapa',
    'Butantã',
    'Vila Romana',
    'Alphaville',
    'Granja Viana',
    'Aclimação',
    'Aguai',
    'Alto de Pinheiros',
    'Alto da Lapa',
    'Bairro do Limão',
    'Belém',
    'Bom Retiro',
    'Bosque da Saúde',
    'Cachoeirinha',
    'Cambuci',
    'Campo Limpo',
    'Casa Verde',
    'Cidade Ademar',
    'Cidade Dutra',
    'Cidade Jardim',
    'Cidade Líder',
    'Cidade Nova Heliópolis',
    'Cidade Tiradentes',
    'Consolação',
    'Freguesia do Ó',
    'Grajaú',
    'Guaianazes',
    'Ibirapuera',
    'Ipiranga',
    'Itaim Paulista',
    'Itaquera',
    'Jabaquara',
    'Jardim América',
    'Jardim Paulista',
    'Jardim Paulistano',
    'Jardim São Luís',
    'Jaraguá',
    'Lajeado',
    'Mandaqui',
    'Moóca',
    'Morumbi',
    'Parelheiros',
    'Parque do Carmo',
    'Penha',
    'Pirituba',
    'Raposo Tavares',
    'Sacomã',
    'Santa Cecília',
    'Santana',
    'Sapopemba',
    'Saúde',
    'Sé',
    'Socorro',
    'Sumaré',
    'Tucuruvi',
    'Vila Andrade',
    'Vila Carrão',
    'Vila Clementino',
    'Vila Curuçá',
    'Vila Ede',
    'Vila Guilherme',
    'Vila Leopoldina',
    'Vila Matilde',
    'Vila Nova Cachoeirinha',
    'Vila Prudente',
    'Vila Sônia',
];

// Principais bairros do Rio de Janeiro
export const RIO_DE_JANEIRO_NEIGHBORHOODS = [
    'Copacabana',
    'Ipanema',
    'Leblon',
    'Barra da Tijuca',
    'Tijuca',
    'Botafogo',
    'Flamengo',
    'Laranjeiras',
    'Catete',
    'Glória',
    'Centro',
    'Lapa',
    'Santa Teresa',
    'Gávea',
    'Jardim Botânico',
    'Vidigal',
    'Rocinha',
    'São Conrado',
    'Barra',
    'Recreio dos Bandeirantes',
    'Jacarepaguá',
    'Campo Grande',
    'Madureira',
    'Maracanã',
    'Vila Isabel',
    'Meier',
    'Ilha do Governador',
    'Alto da Boa Vista',
    'Andaraí',
    'Bangu',
    'Bonsucesso',
    'Caju',
    'Cascadura',
    'Catumbi',
    'Cidade Nova',
    'Cosme Velho',
    'Cosmos',
    'Curicica',
    'Del Castilho',
    'Engenho de Dentro',
    'Engenho Novo',
    'Freguesia',
    'Gamboa',
    'Gávea',
    'Grajaú',
    'Guaratiba',
    'Inhaúma',
    'Jardim América',
    'Jardim Carioca',
    'Jardim Guanabara',
    'Laranjeiras',
    'Lins de Vasconcelos',
    'Mangueira',
    'Méier',
    'Oswaldo Cruz',
    'Pavuna',
    'Penha',
    'Piedade',
    'Praça da Bandeira',
    'Praça Seca',
    'Ramos',
    'Realengo',
    'Rio Comprido',
    'Santa Cruz',
    'São Cristóvão',
    'Senador Vasconcelos',
    'Tanque',
    'Tijuca',
    'Todos os Santos',
    'Turiaçu',
    'Urca',
    'Vaz Lobo',
    'Vigário Geral',
    'Vila Valqueire',
];

// Principais bairros de Salvador
export const SALVADOR_NEIGHBORHOODS = [
    'Barra',
    'Ondina',
    'Rio Vermelho',
    'Pituba',
    'Itaigara',
    'Costa Azul',
    'Imbuí',
    'Stiep',
    'Boca do Rio',
    'Patamares',
    'Jardim Armação',
    'Armação',
    'Piatã',
    'Itapuã',
    'Stella Maris',
    'Floresta',
    'Garcia',
    'Canela',
    'Graça',
    'Vitória',
    'Centro',
    'Pelourinho',
    'Comércio',
    'Cidade Baixa',
    'Federação',
    'Brotas',
    'Alto da Terezinha',
    'Cabula',
    'São Caetano',
    'Iguatemi',
    'Cajazeiras',
    'Pernambués',
    'Lobato',
    'Liberdade',
    'Campo Grande',
    'Calçada',
    'Paripe',
    'São Tomé de Paripe',
    'Alto do Cabrito',
    'Amaralina',
    'Arenoso',
    'Barris',
    'Beiru',
    'Calabar',
    'Caixa D\'Água',
    'Caminho de Areia',
    'Campinas de Brotas',
    'Canabrava',
    'Candeal',
    'Capelinha',
    'Casa Grande',
    'Castelo Branco',
    'Cosme de Farias',
    'Coutos',
    'Curuzu',
    'Dom Avelar',
    'Engenho Velho de Brotas',
    'Engomadeira',
    'Fazenda Grande',
    'Fazenda Coutos',
    'Fazenda Grande do Retiro',
    'Garcia',
    'Granja Rios',
    'IAPI',
    'Ilha Amarela',
    'Jardim Apipema',
    'Jardim Nova Esperança',
    'Jardim das Margaridas',
    'Jardim Santo Inácio',
    'Largo do Tanque',
    'Massaranduba',
    'Nazaré',
    'Nova Brasília',
    'Novo Horizonte',
    'Pero Vaz',
    'Pirajá',
    'Plataforma',
    'Praia do Flamengo',
    'Retiro',
    'Ribeira',
    'São Cristóvão',
    'São Gonçalo',
    'São João do Cabrito',
    'São Marcos',
    'São Rafael',
    'Sete Portas',
    'Simões Filho',
    'Sussuarana',
    'Tancredo Neves',
    'Terreiro de Jesus',
    'Uruguai',
    'Vale das Pedrinhas',
    'Vila Canária',
    'Vila Rica',
];

// Principais bairros de Belo Horizonte
export const BELO_HORIZONTE_NEIGHBORHOODS = [
    'Savassi',
    'Lourdes',
    'Funcionários',
    'Centro',
    'Lagoinha',
    'Santa Tereza',
    'Santo Antônio',
    'Anchieta',
    'Serra',
    'Gutierrez',
    'Carlos Prates',
    'Cidade Jardim',
    'Buritis',
    'Vila Clóris',
    'Alto Barroca',
    'Palmares',
    'Belvedere',
    'Mangabeiras',
    'Pampulha',
    'Ouro Preto',
    'Ermelinda',
    'Santa Inês',
    'Boa Viagem',
    'Bandeirantes',
    'Grajaú',
    'Barro Preto',
    'Floresta',
    'Prado',
    'Nova Suíça',
    'Horto',
    'Acaiaca',
    'Aeroporto',
    'Alto Barroca',
    'Alípio de Melo',
    'Anchieta',
    'Araguaia',
    'Bahia',
    'Barão Homem de Melo',
    'Barreiro',
    'Boa Vista',
    'Bonfim',
    'Cabana',
    'Cachoeirinha',
    'Calafate',
    'Camargos',
    'Carmo',
    'Casa Branca',
    'Castelo',
    'Cidade Nova',
    'Comiteco',
    'Concórdia',
    'Confisco',
    'Coração de Jesus',
    'Coração Eucarístico',
    'Dom Bosco',
    'Dom Cabral',
    'Ermelinda',
    'Europa',
    'Fazendinha',
    'Fernão Dias',
    'Gameleira',
    'Goiânia',
    'Guarani',
    'Gutierrez',
    'Havaí',
    'Horto',
    'Independência',
    'Ipiranga',
    'Itapoã',
    'Jaqueline',
    'Jaraguá',
    'João Pinheiro',
    'Lindéia',
    'Lourdes',
    'Madre Gertrudes',
    'Mantiqueira',
    'Marajó',
    'Marieta',
    'Minaslândia',
    'Mineirão',
    'Nova Cachoeirinha',
    'Nova Floresta',
    'Nova Gameleira',
    'Nova Granada',
    'Nova Vista',
    'Oeste',
    'Olhos D\'Água',
    'Padre Eustáquio',
    'Paraíso',
    'Parque São Pedro',
    'Paquetá',
    'Pedreira Prado Lopes',
    'Pindorama',
    'Pompéia',
    'Pongelupe',
    'Quinta do Sumaré',
    'Renascença',
    'Rio Branco',
    'Ribeiro de Abreu',
    'Sagrada Família',
    'Santa Amélia',
    'Santa Cruz',
    'Santa Efigênia',
    'Santa Lúcia',
    'Santa Mônica',
    'Santa Quitéria',
    'Santa Rosa',
    'Santana',
    'Santo André',
    'São Bento',
    'São Bernardo',
    'São Cristóvão',
    'São Damião',
    'São Francisco',
    'São Gabriel',
    'São Geraldo',
    'São João Batista',
    'São Jorge',
    'São Lucas',
    'São Pedro',
    'São Paulo',
    'São Tomáz',
    'Segredo',
    'Sion',
    'Solar do Barreiro',
    'Suzana',
    'Taquaril',
    'Tupi',
    'União',
    'Venda Nova',
    'Vila Antena',
    'Vila Cemig',
    'Vila Copacabana',
    'Vila da Paz',
    'Vila Estrela',
    'Vila Formosa',
    'Vila Mantiqueira',
    'Vila Minaslândia',
    'Vila Nova',
    'Vila Nova Gameleira',
    'Vila Oeste',
    'Vila Pinho',
    'Vila Sumaré',
    'Xangri-lá',
    'Zilah Sposito',
];

// Principais bairros de Curitiba
export const CURITIBA_NEIGHBORHOODS = [
    'Batel',
    'Centro',
    'Água Verde',
    'Boa Vista',
    'Cristo Rei',
    'Juvevê',
    'Mercês',
    'Rebouças',
    'Ahú',
    'Bigorrilho',
    'Campo Comprido',
    'Jardim Botânico',
    'Tingui',
    'Tarumã',
    'Portão',
    'Novo Mundo',
    'Cidade Industrial',
    'Capão da Imbuia',
    'Santo Inácio',
    'Bom Retiro',
    'Santa Felicidade',
    'Água Verde',
    'Bacacheri',
    'Boa Vista',
    'Orleans',
    'Pilarzinho',
    'Prado Velho',
    'Santa Cândida',
    'Uberaba',
    'Xaxim',
];

// Principais bairros de Porto Alegre
export const PORTO_ALEGRE_NEIGHBORHOODS = [
    'Moinhos de Vento',
    'Bela Vista',
    'Cidade Baixa',
    'Centro Histórico',
    'Bom Fim',
    'Partenon',
    'Cristal',
    'Petrópolis',
    'Auxiliadora',
    'Floresta',
    'Santa Maria Goretti',
    'Santana',
    'Menino Deus',
    'São João',
    'Centro',
    'Navegantes',
    'Tristeza',
    'Cavalhada',
    'Belém Novo',
    'Ipanema',
    'Vila Assunção',
    'Vila Conceição',
    'Glória',
    'Jardim do Salso',
    'Coronel Aparício Borges',
    'Arquipélago',
    'Vila Ipiranga',
    'São Geraldo',
    'Farrapos',
    'Aberta dos Morros',
    'Agronomia',
    'Anchieta',
    'Arquipélago',
    'Auxiliadora',
    'Azenha',
    'Bela Vista',
    'Belém Novo',
    'Belém Velho',
    'Boa Vista',
    'Bom Jesus',
    'Bonfim',
    'Bom Fim',
    'Camaquã',
    'Campo Novo',
    'Cascata',
    'Cavalhada',
    'Centro',
    'Centro Histórico',
    'Chácara das Pedras',
    'Cidade Baixa',
    'Cristal',
    'Espírito Santo',
    'Farrapos',
    'Farroupilha',
    'Floresta',
    'Glória',
    'Guarujá',
    'Hípica',
    'Humaitá',
    'Independência',
    'Ipanema',
    'Jardim Botânico',
    'Jardim Carvalho',
    'Jardim do Salso',
    'Jardim Isabel',
    'Jardim Lindóia',
    'Jardim São Pedro',
    'Lageado',
    'Lami',
    'Lomba do Pinheiro',
    'Marcílio Dias',
    'Mário Quintana',
    'Medianeira',
    'Menino Deus',
    'Moinhos de Vento',
    'Mont\'Serrat',
    'Navegantes',
    'Nonoai',
    'Partenon',
    'Passo da Areia',
    'Passo das Pedras',
    'Pedra Redonda',
    'Petrópolis',
    'Praia de Belas',
    'Protásio Alves',
    'Restinga',
    'Rio Branco',
    'Rubem Berta',
    'Santa Cecília',
    'Santa Maria Goretti',
    'Santa Tereza',
    'Santana',
    'Santo Antônio',
    'São Geraldo',
    'São João',
    'São José',
    'São Sebastião',
    'Sarandi',
    'Serraria',
    'Teresópolis',
    'Três Figueiras',
    'Tristeza',
    'Vila Assunção',
    'Vila Conceição',
    'Vila Ipiranga',
    'Vila Jardim',
    'Vila João Pessoa',
    'Vila Nova',
];

// Principais setores/regiões de Brasília
export const BRASILIA_NEIGHBORHOODS = [
    'Asa Sul',
    'Asa Norte',
    'Lago Sul',
    'Lago Norte',
    'Sudoeste',
    'Noroeste',
    'Águas Claras',
    'Taguatinga',
    'Ceilândia',
    'Guará',
    'Cruzeiro',
    'Sobradinho',
    'Planaltina',
    'Gama',
    'Santa Maria',
    'São Sebastião',
    'Paranoá',
    'Itapoã',
    'SIA',
    'Vicente Pires',
    'Arniqueiras',
    'Águas Claras',
    'Riacho Fundo',
    'Candangolândia',
    'Núcleo Bandeirante',
];

// Principais bairros de Fortaleza
export const FORTALEZA_NEIGHBORHOODS = [
    'Meireles',
    'Aldeota',
    'Dionísio Torres',
    'Praia de Iracema',
    'Centro',
    'Varjota',
    'Papicu',
    'Cocó',
    'Guararapes',
    'Joaquim Távora',
    'Boa Viagem',
    'São Gerardo',
    'Benfica',
    'Rodolfo Teófilo',
    'Parque Manibura',
    'Edson Queiroz',
    'Messejana',
    'Antônio Bezerra',
    'Maraponga',
    'Mondubim',
    'Parangaba',
    'Jardim América',
    'Cambeba',
    'Água Fria',
    'Conjunto Ceará',
    'Jardim Iracema',
    'Cidade dos Funcionários',
    'Álvaro Weyne',
    'Engenheiro Luciano Cavalcante',
];

// Principais bairros de Recife
export const RECIFE_NEIGHBORHOODS = [
    'Boa Viagem',
    'Pina',
    'Piedade',
    'Casa Forte',
    'Graças',
    'Espinheiro',
    'Derby',
    'Torre',
    'Madalena',
    'Aflitos',
    'Poço da Panela',
    'Santo Amaro',
    'Centro',
    'Recife Antigo',
    'São José',
    'Boa Vista',
    'Santo Antônio',
    'Ilha do Leite',
    'Santo Amaro',
    'Barro',
    'Cordeiro',
    'Várzea',
    'Casa Amarela',
    'Tamarineira',
    'Apipucos',
    'Dois Irmãos',
    'Casa Caiada',
    'Imbiribeira',
    'Areias',
];

// Principais bairros de Manaus
export const MANAUS_NEIGHBORHOODS = [
    'Centro',
    'Adrianópolis',
    'Ponta Negra',
    'Aleixo',
    'Chapada',
    'São Geraldo',
    'Parque 10 de Novembro',
    'Dom Pedro',
    'Cidade Nova',
    'Japiim',
    'Alvorada',
    'Educandos',
    'Compensa',
    'Tarumã',
    'São Jorge',
    'Planalto',
    'Nova Cidade',
    'Santa Etelvina',
    'Coroado',
    'Jorge Teixeira',
    'Raiz',
    'Colônia Terra Nova',
    'Monte das Oliveiras',
    'Lago Azul',
    'Lírio do Vale',
    'Novo Aleixo',
    'Cidade de Deus',
    'Japiim',
];

// Principais bairros de Belém
export const BELEM_NEIGHBORHOODS = [
    'Nazaré',
    'Umarizal',
    'Batista Campos',
    'Centro',
    'Reduto',
    'Campina',
    'Comércio',
    'Marco',
    'Souza',
    'Pedreira',
    'Cremação',
    'Jurunas',
    'Condor',
    'Guamá',
    'Terra Firme',
    'Bengui',
    'Entroncamento',
    'Una',
    'Val-de-Cans',
    'Marambaia',
    'Sacramenta',
    'Canudos',
    'Fátima',
    'São Brás',
    'Castanheira',
    'Tenoné',
    'Aurá',
];

// Principais bairros de Goiânia
export const GOIANIA_NEIGHBORHOODS = [
    'Setor Marista',
    'Setor Bueno',
    'Setor Oeste',
    'Jardim América',
    'Setor Central',
    'Campinas',
    'Setor Sul',
    'Setor Norte',
    'Jardim Goiás',
    'Parque Amazônia',
    'Parque Anhanguera',
    'Alto da Glória',
    'Jardim Balneário',
    'Setor Pedro Ludovico',
    'Setor Leste Universitário',
    'Parque Veiga Jardim',
    'Jardim Europa',
    'Setor Coimbra',
    'Setor Jaó',
    'Setor Aeroporto',
    'Residencial Solar Central Park',
    'Vila Redenção',
    'Parque Industrial',
    'Setor Faiçalville',
    'Jardim Nova Esperança',
    'Parque Real de Goiânia',
];

// Principais bairros de Florianópolis
export const FLORIANOPOLIS_NEIGHBORHOODS = [
    'Centro',
    'Trindade',
    'Agronômica',
    'Itacorubi',
    'Lagoa da Conceição',
    'Jurerê Internacional',
    'Canto da Lagoa',
    'Cachoeira do Bom Jesus',
    'Ponta das Canas',
    'Canasvieiras',
    'Joaquina',
    'Praia Mole',
    'Barra da Lagoa',
    'Ingleses',
    'Santinho',
    'Rio Tavares',
    'Campeche',
    'Armação',
    'Pantanal',
    'Coqueiros',
    'Estreito',
    'Balneário',
    'Saco dos Limões',
    'Carianos',
    'Tapera',
    'Carianos',
    'Morro das Pedras',
    'Ribeirão da Ilha',
];

export const NEIGHBORHOODS_BY_CITY: Record<string, string[]> = {
    'São Paulo': SAO_PAULO_NEIGHBORHOODS,
    'Rio de Janeiro': RIO_DE_JANEIRO_NEIGHBORHOODS,
    'Salvador': SALVADOR_NEIGHBORHOODS,
    'Belo Horizonte': BELO_HORIZONTE_NEIGHBORHOODS,
    'Curitiba': CURITIBA_NEIGHBORHOODS,
    'Porto Alegre': PORTO_ALEGRE_NEIGHBORHOODS,
    'Brasília': BRASILIA_NEIGHBORHOODS,
    'Fortaleza': FORTALEZA_NEIGHBORHOODS,
    'Recife': RECIFE_NEIGHBORHOODS,
    'Manaus': MANAUS_NEIGHBORHOODS,
    'Belém': BELEM_NEIGHBORHOODS,
    'Goiânia': GOIANIA_NEIGHBORHOODS,
    'Florianópolis': FLORIANOPOLIS_NEIGHBORHOODS,
};

